name: BDD CI Pipeline

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  bdd-tests:
    name: BDD Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers (cached)
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps chromium

      - name: Build application
        run: npm run build

      - name: Start application
        run: npm start &
        env:
          PORT: 3000

      - name: Wait for app to be ready
        run: |
          sleep 15
          curl -f http://localhost:3000 || exit 1

      - name: Run BDD tests
        run: npm run bdd
        env:
          BASE_URL: http://localhost:3000
        timeout-minutes: 5

      - name: Upload Cucumber HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cucumber-html-report
          path: tests/reports/cucumber-report.html

      - name: Upload Cucumber JSON report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cucumber-json-report
          path: tests/reports/cucumber-report.json

      - name: Generate test summary
        if: always()
        run: |
          echo "## BDD Test Results" >> $GITHUB_STEP_SUMMARY
          echo "Tests completed with status: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "Check artifacts for detailed reports" >> $GITHUB_STEP_SUMMARY
